const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Timeline,
		C3.Plugins.Particles,
		C3.Plugins.Mouse,
		C3.Plugins.TextBox,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Timeline.Acts.PauseTimelineByTags,
		C3.Plugins.Timeline.Acts.ResumeTimelineByTags,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.TextBox.Acts.SetFocus,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Text.Acts.SetText
	];
};
self.C3_JsPropNameTable = [
	{esteira_horizontal: 0},
	{esteira_vertical: 0},
	{Sprite: 0},
	{robo_sao_martin: 0},
	{palete_montado: 0},
	{palete_vazio: 0},
	{pouco_fralda: 0},
	{robo_sao_martin2: 0},
	{Texto: 0},
	{camera: 0},
	{strechadora: 0},
	{robo_zegla1: 0},
	{palete_vazio_: 0},
	{strechadora2: 0},
	{strechadora3: 0},
	{grade_amarela: 0},
	{etiquetadora_Video_jet: 0},
	{leitor_honeyWell: 0},
	{empilhadeira_vazia: 0},
	{empilhadeira_cheia: 0},
	{fim: 0},
	{inicio: 0},
	{pacoteDeFralda: 0},
	{ControladorDaTimeline: 0},
	{reiniciar: 0},
	{tx_reiniciar: 0},
	{pacoteDeFralda2: 0},
	{pacoteDeFralda3: 0},
	{flashCamera: 0},
	{camera2: 0},
	{tx_pausar: 0},
	{Mouse: 0},
	{tx_retomar: 0},
	{usuario: 0},
	{usenha: 0},
	{entrar: 0},
	{tx_entrar: 0},
	{Sprite2: 0}
];

self.InstanceType = {
	esteira_horizontal: class extends self.ISpriteInstance {},
	esteira_vertical: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	robo_sao_martin: class extends self.ISpriteInstance {},
	palete_montado: class extends self.ISpriteInstance {},
	palete_vazio: class extends self.ISpriteInstance {},
	pouco_fralda: class extends self.ISpriteInstance {},
	robo_sao_martin2: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	camera: class extends self.ISpriteInstance {},
	strechadora: class extends self.ISpriteInstance {},
	robo_zegla1: class extends self.ISpriteInstance {},
	palete_vazio_: class extends self.ISpriteInstance {},
	strechadora2: class extends self.ISpriteInstance {},
	strechadora3: class extends self.ISpriteInstance {},
	grade_amarela: class extends self.ISpriteInstance {},
	etiquetadora_Video_jet: class extends self.ISpriteInstance {},
	leitor_honeyWell: class extends self.ISpriteInstance {},
	empilhadeira_vazia: class extends self.ISpriteInstance {},
	empilhadeira_cheia: class extends self.ISpriteInstance {},
	fim: class extends self.ISpriteInstance {},
	inicio: class extends self.ISpriteInstance {},
	pacoteDeFralda: class extends self.ISpriteInstance {},
	ControladorDaTimeline: class extends self.IInstance {},
	reiniciar: class extends self.ISpriteInstance {},
	tx_reiniciar: class extends self.ITextInstance {},
	pacoteDeFralda2: class extends self.ISpriteInstance {},
	pacoteDeFralda3: class extends self.ISpriteInstance {},
	flashCamera: class extends self.IParticlesInstance {},
	camera2: class extends self.ISpriteInstance {},
	tx_pausar: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	tx_retomar: class extends self.ITextInstance {},
	usuario: class extends self.ITextInputInstance {},
	usenha: class extends self.ITextInputInstance {},
	entrar: class extends self.ISpriteInstance {},
	tx_entrar: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {}
}